# Generated by Django 6.0.2 on 2026-03-16 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeitem',
            name='dish_product',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='products',
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('name',), 'verbose_name': 'Ястие', 'verbose_name_plural': 'Ястия'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='description',
        ),
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Калории'),
        ),
        migrations.AddField(
            model_name='dish',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Въглехидрати'),
        ),
        migrations.AddField(
            model_name='dish',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Мазнини'),
        ),
        migrations.AddField(
            model_name='dish',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Бележка'),
        ),
        migrations.AddField(
            model_name='dish',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белтъчини'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Ястие'),
        ),
        migrations.DeleteModel(
            name='RecipeItem',
        ),
    ]
