# Generated by Django 6.0.2 on 2026-03-16 22:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_category'),
        ('meals', '0002_remove_recipeitem_dish_product_remove_dish_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, help_text='Количество от продукта за приготвяне на ястието.', max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meals.dish', verbose_name='Ястие')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='inventory.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Съставка на ястие',
                'verbose_name_plural': 'Съставки на ястия',
                'ordering': ('dish', 'product__name'),
                'unique_together': {('dish', 'product')},
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='dishes', through='meals.DishIngredient', to='inventory.product', verbose_name='Продукти'),
        ),
    ]
