# Generated by Django 6.0.2 on 2026-03-16 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_dishingredient_dish_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishingredient',
            options={},
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
