# Generated by Django 6.0.2 on 2026-03-16 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_dishingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishingredient',
            options={'ordering': ('dish', 'product__name'), 'verbose_name': 'Съставка на ястие'},
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=0, help_text='Количество от продукта за ястието.', max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
