# Generated by Django 6.0.2 on 2026-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_dishingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Забележка*'),
        ),
    ]
