# Generated by Django 6.0.2 on 2026-03-17 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_category'),
        ('meals', '0006_alter_dish_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishingredient',
            options={'ordering': ('dish', 'product__name'), 'verbose_name': 'Съставка на ястие', 'verbose_name_plural': 'Съставки на ястия'},
        ),
        migrations.AlterUniqueTogether(
            name='dishingredient',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Бележка'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=0, help_text='Количеството от продукта, което се използва в ястието.', max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AddConstraint(
            model_name='dishingredient',
            constraint=models.UniqueConstraint(fields=('dish', 'product'), name='unique_product_per_dish'),
        ),
    ]
