# Generated by Django 6.0.2 on 2026-03-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('meat_fish', 'Месо, риба, яйца'), ('milk_cheese', 'Млечни продукти'), ('grains_legumes', 'Зърнени храни и бобови'), ('fruit_vegetables', 'Плодове и зеленчуци'), ('nuts_oils', 'Ядки и мазнини'), ('desserts_sweets', 'Десерти и сладки храни'), ('drinks', 'Напитки'), ('packaged_store', 'Готови храни')], default='grains_legumes', max_length=30, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
