# Generated by Django 6.0.2 on 2026-03-15 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='available_quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Налично количество'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='minimum_quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимално количество'),
        ),
    ]
