# Generated by Django 6.0.2 on 2026-03-15 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='available_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Налично количество'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='minimum_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимално количество'),
        ),
    ]
