# Generated by Django 6.0.2 on 2026-03-16 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_available_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'brand']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='available_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Налично количество'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='minimum_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимално количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories_per_100',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Калории / 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs_per_100',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Въглехидрати / 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat_per_100',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Мазнини / 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein_per_100',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белтъчини / 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'Грамове (g)'), ('pcs', 'Опаковка / брой')], max_length=10, verbose_name='Мерна единица'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
