# Generated by Django 6.0.2 on 2026-03-16 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_store_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['product__name'], 'verbose_name': 'Наличност', 'verbose_name_plural': 'Наличности'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'brand'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='minimum_quantity',
            field=models.DecimalField(decimal_places=0, default=0, help_text='При падане под минимално - продукта влиза в списъка за пазаруване.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимално количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories_per_100',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kcal / 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_basic',
            field=models.BooleanField(default=False, help_text='Основен продукт- трябва да има наличност.', verbose_name='Базов продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'Грамове (g)'), ('pcs', 'Брой')], max_length=10, verbose_name='Мерна единица'),
        ),
    ]
