# Generated by Django 6.0.2 on 2026-03-16 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbs_per_100',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Въглехидрати / 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat_per_100',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Мазнини / 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein_per_100',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Белтъчини / 100g'),
        ),
    ]
