# Generated by Django 6.0.2 on 2026-03-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_carbs_per_100_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('meat_fish', 'Месо, риба, яйца'), ('milk_cheese', 'Млечни продукти'), ('grains_legumes', 'Зърнени храни и бобови'), ('fruit_vegetables', 'Плодове и зеленчуци'), ('nuts_oils', 'Ядки и мазнини'), ('desserts_sweets', 'Десерти и сладки'), ('drinks', 'Напитки'), ('packaged_store', 'Готови храни'), ('spices', 'Подправки')], max_length=30, verbose_name='Категория'),
        ),
    ]
