# Generated by Django 6.0.2 on 2026-03-16 00:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_store_alter_product_options_and_more'),
        ('weekmenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ('day', 'id'), 'verbose_name': 'Запис в меню', 'verbose_name_plural': 'Записи в меню'},
        ),
        migrations.AlterModelOptions(
            name='weekmenu',
            options={'ordering': ('-start_date',), 'verbose_name': 'Седмично меню', 'verbose_name_plural': 'Седмични менюта'},
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='meal',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='meal',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=100, help_text='За продукт: грамове или брой. За ястие може да оставиш 1.', max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='eating_out',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
    ]
