# Generated by Django 6.0.2 on 2026-03-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekmenu', '0002_alter_meal_options_alter_weekmenu_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeekMenu',
            new_name='WeekMenuModel',
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ('day', 'id'), 'verbose_name': 'Запис в меню', 'verbose_name_plural': 'Записа в меню'},
        ),
    ]
