# Generated by Django 6.0.2 on 2026-03-17 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekmenu', '0003_rename_weekmenu_weekmenumodel_alter_meal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ('day', 'id'), 'verbose_name': 'Запис в меню', 'verbose_name_plural': 'Записи в меню'},
        ),
        migrations.AlterField(
            model_name='meal',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=100, help_text='За продукт – грамове или брой. За ястие обикновено остава 1.', max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='weekmenumodel',
            name='start_date',
            field=models.DateField(unique=True, verbose_name='Начален ден на седмицата'),
        ),
    ]
